### ISSUE TITLE
useLocation is wrong at start

### ISSUE THREAD

**Issue by yoanngueny** [cher-ami/router#36]
`location` value is `/` when reloading page from another route.

**Comment by willybrauner** [comment]
This is only on HASH history mode. Because this mode allows to not specify a base path, his first route path is always "/" if no hash is set in URL. 

url : `http://localhost:1234/about`

history location first object: 
```js
{pathname: "/", search: "", hash: "", state: null, key: "default"}
```


If you want "the right pathname" on first load in history location array with HASH mode, you need start your path by the hash #.

url : `http://localhost:1234/#/about`

history location first object: 
```js
{pathname: "/about", search: "", hash: "", state: null, key: "default"}
```

**Comment by yoanngueny** [comment]
I confirm, there is no problem in default mode.

But, the problem exist in HASH mode.
For exemple, when I load this url `http://localhost:3000/#/discover-home`, `location` return `/`.

**Comment by willybrauner** [comment]
My bad, default value of location is depend of `window.location` and not of `ROUTERS.history.location`.
